version: '2'

# USAGE (from root directory): docker-compose -f ./setup/<docker-compose>.yml up
services:

  wordpress:
    extends:
      # relative to the position of current file.
      file: ./wordpress.docker-compose.yml
      service: wordpress
    build:
      context: ../../
      dockerfile: ./setup/container/wordpress.php5.6.dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ../../distribution:/tmp/distribution/
      - ../../content:/tmp/content/
      - ../../setup/shellScript:/tmp/shellScript/

  mysql:
    extends:
      file: ./mysql.docker-compose.yml
      service: mysql

  phpmyadmin:
    extends:
      file: ./phpmyadmin.docker-compose.yml
      service: phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql:db

