version: '3'

# USAGE (from root directory): docker-compose -f ./setup/<docker-compose>.yml up
networks: 
  default:
    external: false

services:

  wordpress:
    image: myuserindocker/dentristwebapp:latest
    container_name: wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../../volume/app:/app/"
      - "../../volume/log:/var/log/apache2/"
    environment:
      DEPLOYMENT: production
      # WORDPRESS_DB_USER: MyUserIn8D
      # WORDPRESS_DB_PASSWORD: <g.,qPE:9U>21#B](
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: WebApp_Dentrist_Database
      # WORDPRESS_TABLE_PREFIX: c2xj4zrxos_
      WORDPRESS_DB_HOST: mysql:3306
    # entrypoint: updateDefaultEntrypoint.sh
    restart: always
    networks:
      - default

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    volumes:
        # - "./../volume/mysqlDatabase/:/var/lib/mysql"
        - "../../volume/mysqlDatabase/:/docker-entrypoint-initdb.d"
    environment:
        # MYSQL_ROOT_PASSWORD: wordpress
        # # MYSQL_USER: MyUserIn8D
        # # MYSQL_PASSWORD: <g.,qPE:9U>21#B](
        # MYSQL_DATABASE: WebApp_Dentrist_Database
        MYSQL_ROOT_PASSWORD: wordpress
        # MYSQL_USER: MyUserIn8D
        # MYSQL_PASSWORD: <g.,qPE:9U>21#B](
        MYSQL_DATABASE: WebApp_Dentrist_Database
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - /sessions
    container_name: phpmyadmin
    ports:
     - 81:80
    # IMPORTANT: Check if extrahosts work. (How does "mysql" host translated to "db" host for usage in phpmyadmin when yaml version 3 is used.)
    # links:
    #   - mysql:db
    extra_hosts:
      - "mysql:db"
    networks:
      - default
