version: '2.1'

# USAGE (from root directory): docker-compose -f ./setup/<docker-compose>.yml up
services:

  wordpress:
    extends:
      # relative to the position of current file.
      file: ./wordpress.dockerCompose.yml
      service: wordpressImage
    restart: always
    depends_on:
      - mysql 
    links:
      - mysql

  mysql:
    extends:
      file: ./mysql.dockerCompose.yml
      service: mysql

  phpmyadmin:
    extends:
      file: ./phpmyadmin.dockerCompose.yml
      service: phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql:db
