version: '2.1'

services:

  wordpress:
    container_name: wordpress
    ports:
      - "80:80"
      - "443:443"
    # All mounted volumes with specific host directory, replace the contents/files of the container folder. Thus the solution is to use entrypoint to populate the volume after it is created.
    # volumes:
    environment:
      DEPLOYMENT: 'production'
      WORDPRESS_DB_HOST: mysql:3306
      # WORDPRESS_DB_USER: MyUserIn8D
      # WORDPRESS_DB_PASSWORD: <g.,qPE:9U>21#B](
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: WebApp_Dentrist_Database
      # WORDPRESS_TABLE_PREFIX: c2xj4zrxos_
    # entrypoint: updateDefaultEntrypoint.sh
 
  wordpressImage:
    extends: wordpress
    image: myuserindocker/dentristwebapp:latest

  wordpressBuild:
    extends: wordpress
    build:
      context: ../../
      dockerfile: ./setup/container/wordpress.php5.6.dockerfile
      args:
        - DEPLOYMENT=${DEPLOYMENT:-production}
    # name of local image to be built
    environment:
        DEPLOYMENT: ${DEPLOYMENT:-production}
    image: dentrist-${DEPLOYMENT:-production}
